// Code generated by goctl. DO NOT EDIT.
// Source: demo.proto

package rpcdemo

import (
	"context"

	"rpc-demo/rpc-demo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HelloRequest  = rpc_demo.HelloRequest
	HelloResponse = rpc_demo.HelloResponse

	RpcDemo interface {
		Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	}

	defaultRpcDemo struct {
		cli zrpc.Client
	}
)

func NewRpcDemo(cli zrpc.Client) RpcDemo {
	return &defaultRpcDemo{
		cli: cli,
	}
}

func (m *defaultRpcDemo) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	client := rpc_demo.NewRpcDemoClient(m.cli.Conn())
	return client.Hello(ctx, in, opts...)
}
