// Code generated by goctl. DO NOT EDIT.
// Source: demo.proto

package server

import (
	"context"

	"rpc-demo/internal/logic"
	"rpc-demo/internal/svc"
	"rpc-demo/rpc-demo"
)

type RpcDemoServer struct {
	svcCtx *svc.ServiceContext
	rpc_demo.UnimplementedRpcDemoServer
}

func NewRpcDemoServer(svcCtx *svc.ServiceContext) *RpcDemoServer {
	return &RpcDemoServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcDemoServer) Hello(ctx context.Context, in *rpc_demo.HelloRequest) (*rpc_demo.HelloResponse, error) {
	l := logic.NewHelloLogic(ctx, s.svcCtx)
	return l.Hello(in)
}
